$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: batch-v1
endpoint_name: water-intel-batch
type: model
model:
  path: azureml:water-leak-model:1
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
code_configuration:
  code: ./
  scoring_script: ml/deployment/score.py
compute: azureml:cpu-cluster
mini_batch_size: "100"
retry_settings:
  max_retries: 3
  timeout: 120
